name: Bug report
description: Report a problem or unexpected behavior.
title: "[Bug]: "
labels: [bug, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and didn't find a duplicate
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Multi-account switching
        - Slack remote access
        - Session migration
        - CLI / setup
        - Webhook
        - Hooks
        - Other
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating system
      options:
        - macOS
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: Version
      description: Output of `claude-nonstop --version` and `node --version`
      placeholder: "claude-nonstop 0.2.0, node v22.0.0"
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: A clear description of the bug.
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      description: Minimal steps to reproduce the behavior.
      value: |
        1.
        2.
        3.
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs or screenshots
      description: Paste relevant logs or add screenshots. Redact any tokens or secrets.
    validations:
      required: false
