name: Feature request
description: Suggest an idea or improvement.
title: "[Feature]: "
labels: [enhancement, needs-triage]
body:
  - type: checkboxes
    attributes:
      label: Checklist
      options:
        - label: I searched existing issues and discussions and didn't find a duplicate
          required: true

  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - Multi-account switching
        - Slack remote access
        - Session migration
        - CLI / setup
        - Webhook
        - Hooks
        - Other
    validations:
      required: true

  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the problem you're trying to solve or the opportunity you see.
    validations:
      required: true

  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed solution
      description: What would you like claude-nonstop to do?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any other approaches you've considered?
    validations:
      required: false

  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Links, screenshots, or related issues.
    validations:
      required: false
